[package]
name = "pyramid_legacy_dotx_loader"
version = "0.1.0"
authors = ["Fredrik Noren <fredrik.jw.noren@gmail.com>"]

[dependencies]
peg = "0.3.0"
time = "*"
cgmath = "*"

[dependencies.pyramid]
path = "../pyramid"

[dependencies.ppromise]
path = "../ppromise"
